refactor

diff --git a/files/usr/local/bin/provision-user b/files/usr/local/bin/provision-user
--- a/files/usr/local/bin/provision-user
+++ b/files/usr/local/bin/provision-user
@@ -1,84 +1,149 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+function _message() {
+  caller=$(echo "${FUNCNAME[1]}")
+  base_message=$(echo "$caller" | sed -r 's/(\<|_)([[:alnum:]])/\U \2/g')
+  printf "⮀ %s...\n" "${base_message}"
+}
 
-#####################################################################
-# These env vars are set within the kdk docker image upon startup from the
-#   ~/.kdk/kdk/config.yaml.  However, if we're running the packer vagrant image of
-#   the kdk, these are not passed in.  Set sane defaults for packer.
-KDK_SHELL=${KDK_SHELL:-$SHELL}
-KDK_DOTFILES_REPO=${KDK_DOTFILES_REPO:-https://github.com/cisco-sso/yadm-dotfiles.git}
-if [ -z "${KDK_USERNAME+x}" ]; then
-  # Set KDK_USERNAME to be $SUDO_USER if exists, otherwise $USER
-  if [ ! -z "${SUDO_USER+x}" ]; then
-    KDK_USERNAME=${SUDO_USER}
-  else
-    KDK_USERNAME=${USER}
-  fi
-fi
-#####################################################################
-
-OS=$(grep "^ID" /etc/os-release | cut -d= -f2) # ubuntu | debian | centos
-SUDO_GROUP=$([ "$OS" == "centos" ] && echo "wheel" || echo "sudo")
-
-if [[ ! -f "/etc/kdk/provisioned" ]]; then
-  # Check if user exists. If not, create
-  if ! getent passwd ${KDK_USERNAME} 2>&1 >/dev/null; then
-    useradd ${KDK_USERNAME} -m -G ${SUDO_GROUP},users,docker -s ${KDK_SHELL} >/dev/null 2>&1
-  fi
-
-  # Check if user is not in docker group.  If not, add them
-  #   For vagrant, the user may already exist but not be in the group
-  if ! groups ${KDK_USERNAME} | grep -E ' docker\s?' 2>&1 >/dev/null; then
-    usermod -a -G docker ${KDK_USERNAME}
-  fi
-
-  # Check if .ssh dir exists
-  if [[ ! -d /home/${KDK_USERNAME}/.ssh/ ]]; then
-    install -d -o ${KDK_USERNAME} -g ${KDK_USERNAME} -m 0700 /home/${KDK_USERNAME}/.ssh
-  fi
-
-  # Check if ~/.ssh/authorized_keys exists. If not and /tmp/id_rsa.pub exists then cp
-  if [[ ! -f /home/${KDK_USERNAME}/.ssh/authorized_keys ]]; then
-    if [[ -f /tmp/id_rsa.pub ]]; then
-      install -o ${KDK_USERNAME} -g ${KDK_USERNAME} -m 0600 /tmp/id_rsa.pub /home/${KDK_USERNAME}/.ssh/authorized_keys
+function main() {
+    if [ "$#" -eq 0 ]; then
+        echo "Must provide script arg with name of function to be called"
+        exit 1
     else
-      echo "Public key file not found at /tmp/id_rsa.pub"
-      exit 1
+        # If this script was called with arguments, then we build for docker
+        #   The following expects the first argument to be the function name
+        "$@"
+    fi
+}
+
+function set_required_vars() {
+  _message
+  export KDK_SHELL=${KDK_SHELL:-$SHELL}
+  export KDK_DOTFILES_REPO=${KDK_DOTFILES_REPO:-https://github.com/cisco-sso/yadm-dotfiles.git}
+  if [ -z "${KDK_USERNAME+x}" ]; then
+    # Set KDK_USERNAME to be $SUDO_USER if exists, otherwise $USER
+    if [[ -n "${SUDO_USER+x}" ]]; then
+      export KDK_USERNAME=${SUDO_USER}
+    else
+      export KDK_USERNAME=${USER}
     fi
   fi
+  OS=$(grep "^ID" /etc/os-release | cut -d= -f2) # ubuntu | debian | centos
+  SUDO_GROUP=$([ "$OS" == "centos" ] && echo "wheel" || echo "sudo")
+}
 
-  # Set no password for sudo users
+function mark_provisioned() {
+  _message
+  if [[ ! -f "/etc/kdk/provisioned" ]]; then
+    mkdir -p /etc/kdk && echo 1 >/etc/kdk/provisioned
+  fi
+}
+
+function provisioned() {
+  if [[ -f "/etc/kdk/provisioned" ]]; then
+    echo "Already provisioned since exists: /etc/kdk/provisioned"
+    return 0
+  else
+    return 1
+  fi
+}
+
+function provision_user() {
+  _message
+  if ! getent passwd "${KDK_USERNAME}" >/dev/null 2>&1 ; then
+    # echo "  ⮀ Create user..."
+    useradd "${KDK_USERNAME}" -m -G "${SUDO_GROUP}",users,docker -s "${KDK_SHELL}" >/dev/null 2>&1
+  fi
+  if ! groups "${KDK_USERNAME}" | grep -E ' docker\s?' >/dev/null 2>&1; then
+    # echo "  Add user to docker group..."
+    usermod -a -G docker "${KDK_USERNAME}"
+  fi
+  # echo "  Set no password for sudoers"
   if [[ "$OS" == "centos" ]]; then
     sed -i 's@^# %wheel@%wheel@g' /etc/sudoers
   else
     sed -i 's@\%sudo\tALL=(ALL:ALL) ALL@\%sudo\tALL=(ALL) NOPASSWD:ALL@g' /etc/sudoers
   fi
+}
 
-  if [[ -d "/home/linuxbrew" ]]; then
-    export TMP_DIR=$(mktemp -d -t XXXXXXXXXX)
-    mv /home/linuxbrew/.linuxbrew/ ${TMP_DIR}
-    mv ${TMP_DIR}/.linuxbrew/ /home/linuxbrew/
-    rm -fr ${TMP_DIR}
-    echo "meow"
-    chown -R ${KDK_USERNAME}:users /home/linuxbrew
+function provision_ssh() {
+  _message
+  if [[ ! -d "/home/${KDK_USERNAME}/.ssh/" ]]; then
+    # echo "  Create /home/${KDK_USERNAME}/.ssh/"
+    install -d -o "${KDK_USERNAME}" -g "${KDK_USERNAME}" -m 0700 /home/"${KDK_USERNAME}"/.ssh
   fi
-  # Ensure permissions for a few locations
-  chown ${KDK_USERNAME}:${KDK_USERNAME} /home/${KDK_USERNAME}
+  # echo "  Add KDK authorized keys"
+  if [[ ! -f /home/${KDK_USERNAME}/.ssh/authorized_keys ]]; then
+    if [[ -f /tmp/id_rsa.pub ]]; then
+      install -o "${KDK_USERNAME}" -g "${KDK_USERNAME}" -m 0600 /tmp/id_rsa.pub /home/"${KDK_USERNAME}"/.ssh/authorized_keys
+    else
+      echo "  Public key file not found at /tmp/id_rsa.pub"
+      exit 1
+    fi
+  fi
+}
+
+function fix_home_perms() {
+  _message
+  chown "${KDK_USERNAME}":"${KDK_USERNAME}" /home/"${KDK_USERNAME}"
   for item in config cache local; do
     ITEM_PATH="/home/${KDK_USERNAME}/.${item}"
     if [[ -d "${ITEM_PATH}" ]]; then
-      chown -R ${KDK_USERNAME}:${KDK_USERNAME} ${ITEM_PATH}
+      chown -R "${KDK_USERNAME}":"${KDK_USERNAME}" "${ITEM_PATH}"
     fi
   done
-  if [[ -d /go ]]; then
-    chown -R ${KDK_USERNAME}:${KDK_USERNAME} /go
-  fi
-  install -m 0600 -o ${KDK_USERNAME} /dev/null /var/log/kdk-provision.log
+}
 
-  # Setup yadm dotfiles
-  if runuser -l ${KDK_USERNAME} -c "source /etc/profile && yadm clone --bootstrap ${KDK_DOTFILES_REPO}" >>/var/log/kdk-provision.log 2>&1; then
+
+function fix_go_perms() {
+  _message
+  if [[ -d /go ]]; then
+    chown -R "${KDK_USERNAME}":"${KDK_USERNAME}" /go
+  fi
+}
+
+function brew_fix_write(){
+  _message
+    if [[ -d "/home/linuxbrew" ]]; then
+      TMP_DIR=$(mktemp -d -t XXXXXXXXXX)
+      mv /home/linuxbrew/.linuxbrew/ "${TMP_DIR}"
+      mv "${TMP_DIR}"/.linuxbrew/ /home/linuxbrew/
+      rm -fr "${TMP_DIR}"
+    fi
+}
+
+function brew_fix_ownership(){
+  _message
+  if [[ -d "/home/linuxbrew" ]]; then
+    chown -R "${KDK_USERNAME}":users /home/linuxbrew
+  fi
+}
+
+function provision_yadm(){
+  _message
+  if [[ ! -d "/home/${KDK_USERNAME}/.config/yadm/repo.git" ]]; then
+    su --shell "${KDK_SHELL}" - "${KDK_USERNAME}" << EOF
+    source /etc/profile
+    yadm clone --no-bootstrap "${KDK_DOTFILES_REPO}" >> /var/log/kdk-provision.log 2>&1
+    /home/${KDK_USERNAME}/.config/yadm/bootstrap
+EOF
     mkdir -p /etc/kdk
     echo 1 >/etc/kdk/provisioned
   fi
-fi
+}
+function provision(){
+  _message
+  set_required_vars
+  set -euo pipefail
+  provision_user
+  install -m 0600 -o "${KDK_USERNAME}" /dev/null /var/log/kdk-provision.log
+  provision_ssh
+  fix_home_perms
+  fix_go_perms
+
+  provision_yadm
+}
+#####################################################################
+# Run the main program
+main "$@"
